# Site settings
title: Open Supporter Data Interface Documentation
subtitle: ""
email: info@opensupporter.org
description: "The Open Supporter Data Interface (OSDI) effort seeks to define an API and data structures for interoperability among products in the progressive cause-based, campaign and non-profit marketplace."
baseurl: "/osdi-docs"
url: "http://opensupporter.org/"

source_description: Information about the source where this person record was acquired. Eg “Ref74”

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/opensupporter/osdi-docs'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference']
]

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
kramdown:
    input: GFM

